

[env:default]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip		; Arduino 3.x framework
; platform = espressif32																							; Arduino 2.x framework
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
lib_extra_dirs = 
	modules



; 