
[platformio]
default_envs = default


[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip		; Arduino 3.x framework
; platform = espressif32																							; Arduino 2.x framework
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8


[env:default]



[env:local]
build_flags =
	-D MQTT_HOST=\"xxx.xxx.x.xxx\"
	-D MQTT_PORT=1883
	-D ALLOW_INSECURE_MQTT




; OPTIONAL BUILD FLAGS:
	
	; ---- connection / security (all tiers) ----
	; -D MQTT_HOST=\"xxx.xxx.x.xxx\"				; define a different MQTT host; default is "ota.ohioiot.com"
	; -D MQTT_PORT=1883						 	    ; define a different MQTT port; default is 8883
	; -D ALLOW_INSECURE_MQTT						; define this flag to allow insecure MQTT on a local broker - it bypasses TLS
	; -D MQTT_USER=\"xxx\"							; this pulls from credentials unless you define it here
	; -D MQTT_PASS=\"xxxxxxxxxxxxxxxxxxxxxxx\"		; this pulls from credentials unless you define it here
	; -D CA_CERT=xxxx			        			; define a new CA cert for both MQTT and OTA; defaults to OhioIoT's CA certificate (letsencrypt)

	; ---- provisioning (champion only) ----
	; -D AP_SSID=\"xxxxxxxxxxxxxxx\"		        ; rename the SSID for your provisioner; defaults to "DEVICE PROVISIONING"
	
	; ---- OTA (champion only) ----
	; -D OTA_HOST=\"xxxxxxxxxxxxxxxxxxxxxxxxxxxx\"  ; define a new OTA endpoint; defaults to https://ota.ohioiot.com
	; -D OTA_SOCKET_TIMEOUT=xxx					 	; milliseconds before OTA stops waiting for a response from the server for an individual pull; defaults to 10000
	; -D OTA_MAX_DURATION=xxxxxx					; total milliseconds before OTA aborts the download process; default is 300000
	; -D ROLLBACK_THRESHOLD=xxx						; time (ms) by which a user must accept the firmware when manual acceptance is required; default is 600000
	; -D OTA_PROGRESS_INCREMENT=xx				    ; percentage increment between OTA status reports; default is 1 (%)
	; -D REQUIRE_MANUAL_FIRMWARE_ACCEPT 			; require manual confirm of new firmware; if user doesn't send manual acceptance, device rolls back after rollback_threshold

